### PR TITLE
Naskew/muse 103 updated our mission component

### PR DESCRIPTION
**Pull request by nolanaskew**
### 
ss1
ss2

### CODE REVIEW

**Review by tbatk — CHANGES_REQUESTED** [review]
This is awesome! The only changes I would suggest are making the astronaut a bit bigger on mobile, and making it so there's a little bit of margin on the left side.

**Comment by nolanaskew** [comment]
> This is awesome! The only changes I would suggest are making the astronaut a bit bigger on mobile, and making it so there's a little bit of margin on the left side.
###
Done and done!
###
ss2
ss1

**Review by rluberto — APPROVED** [review]
Thanks for getting the changes that @trevormangrum requested done! Everything else looks really good and matches the design very well.

**Review by tbatk — APPROVED** [review]
Looks good! Thank you for making those changes.

**Pull request merged**
