### PR TITLE
Adds Square SDK package, Square client, and Square token refresh

### PR DESCRIPTION
**Pull request by jacob-armiger**
### Jira Issue ID(s)
MUSE-23
### Changes
See pull request #16 for detailed changes. That branch was created from #10 instead of our main develop branch, which resulted in strange conflicts. This new pull request should merge without issues!

### CODE REVIEW

**Review by tbatk — APPROVED** [review]
Looks good! Great work!

**Review by rluberto — APPROVED** [review]
Everything looks good! It will be very useful in order to help integrate Square!

**Comment by jacob-armiger** [comment]
I'm not authorized to merge this PR btw!

**Comment by tbatk** [comment]
> I'm not authorized to merge this PR btw!

Ray and I will look into what's going o and try to have it fixed by the dev meeting tomorrow. For now, feel free to work on other issues.

**Comment by rluberto** [comment]
> I'm not authorized to merge this PR btw!

@jacob-armiger You should be good now.

**Pull request merged**
