### PR TITLE
Initial View Component

### PR DESCRIPTION
**Pull request by rluberto**
### Jira Issue ID(s)

MUSE-21

### Changes

- Created initial view component
- Added invisible container behind the header to prevent body content from being overlapped by the header

### Screenshots (if needed)

image
image

### CODE REVIEW

**Review by tbatk — DISMISSED** [review]
Looks great! I really like the icons and animations you put in!

**Comment by nolanaskew** [comment]
LGTM! Mobile looks especially good

**Review by nolanaskew — DISMISSED** [review]

**Review by jovanyoshioka — DISMISSED** [review]
Beautiful! The only thing I noticed from the screenshots is that the bottom yellow/orange gear seems to be cut off by the next element on the page. I think it might look nice if it were to overflow onto the next container a little bit to let the page "flow." Maybe not overflow onto the footer, but once the other components of the home page are added, overflow onto them. What do you think?

**Comment by rluberto** [comment]
> Beautiful! The only thing I noticed from the screenshots is that the bottom yellow/orange gear seems to be cut off by the next element on the page. I think it might look nice if it were to overflow onto the next container a little bit to let the page "flow." Maybe not overflow onto the footer, but once the other components of the home page are added, overflow onto them. What do you think?

Yes, I think that will help everything flow better. After looking at the design I also noticed that it has the gear overlapping the next container, and I think that that way looks much better. I will work on that and get those changes pushed shortly.

**Pull request merged**
