### PR TITLE
Adds checkout and order placement for ecommerce

### PR DESCRIPTION
**Pull request by tbatk**
### Jira Issue ID(s)
MUSE-101

### Changes
This PR wraps up the major functions of the ecommerce portion of the site. Through the cart page, users are now able to place orders. Upon clicking the proceed to checkout button at the bottom of the cart page, they will be redirected to a Square-hosted checkout form where they will pay for their order. I decided that the Square Checkout form would be best to use because it helps avoid worrying about things like PCI-compliance and Square's weird embedded payment form that could've potentially caused problems with hosting later down the line. There a few minor things that will have to be added to the ecommerce portion of the site in the future, including: 
* Taxes and other fees that the MUSE may have on their products are currently not implemented. We will have to go back in and add these later.
* The cart cookie is currently deleted as soon as the checkout link is created. This could be problematic if a user goes to the checkout page but decides not to buy. Upon returning to the MUSE site, their cart will be gone. We may have to find a workaround for this.
* The ecommerce system on the site currently only supports items with one variation. We need to add items with multiple variations into Square and add support for those.
Please let me know if I need to change anything.
### Screenshots (if needed)
Square Checkout Form
Screen Shot 2021-06-21 at 12 04 14 PM

### CODE REVIEW

**Review by nolanaskew — APPROVED** [review]
Wow! This looks great. Can't wait to see this added to the site

**Comment by jacob-armiger** [comment]
This looks clean. Does the Square-hosted checkout site include an order confirmation page/e-receipt? I'm wondering if creating our own confirmation page would be redundant.

**Review by jacob-armiger — APPROVED** [review]
This is a good solution for the site checkout page

**Review by rluberto — APPROVED** [review]
Everything looks great. I'm glad that you went with the Square checkout because it decreases any issues that we may have with PCI. Thanks for getting this done.

**Pull request merged**
