### PR TITLE
Adds GraphQL queries for Exhibits in Contentful

### PR DESCRIPTION
**Pull request by tbatk**
### Jira Issue ID(s)
MUSE-89
### Changes
This PR implements some GraphQL queries for fetching from the Exhibits content model in Contentful. The use of GraphQL in the Contentful backend will make writing our backend functions significantly easier.  Instead of having to write lengthy, somewhat-confusing functions to fetch data from Contentful, we can do the following:
### The Client
This client is what we will use to actually run our queries. Wherever a query needs to be run, whether it be in a frontend component or an API route, this must be imported to run the query.

Screen Shot 2021-02-22 at 12 14 37 AM

### Get All Exhibits
This query fetches all of the exhibits from Contentful:

Screen Shot 2021-02-22 at 12 11 47 AM

### General Query Format
The basic format for a query in GraphQL is something like this: 
```
query <QUERY_NAME> {
     <CONTENT_MODEL_ID>Collection { 
            items {
              <PARAMETERS_TO_RETURN>
            }

     }
}
```

`<QUERY_NAME>` can be anything, `<CONTENT_MODEL_ID>` can be found when you click on a Content Model in Contentful, and `<PARAMETERS_TO_RETURN>` would be the fields defined for that content model

### Get Exhibit and Queries with Parameters
Queries can have parameters, like this query that gets an exhibit by its name:

Screen Shot 2021-02-22 at 10 16 00 AM

Parameters are passed in when the query is called.

Please let me know if I need to change anything or if y'all have any questions.

### CODE REVIEW

**Review by rluberto — APPROVED** [review]
Everything looks great to me. Hopefully this will be an easier way to get all of the exhibits!

**Comment by kemalfidan** [comment]
LGTM

**Comment by kemalfidan** [comment]
> LGTM

Ship it

**Review by jacob-armiger — APPROVED** [review]
Awesome! Glad you could streamline the process for fetching data from Contentful.

**Review by jovanyoshioka — APPROVED** [review]
Very cool. This looks like it will make querying data a lot easier. Great work!

**Review by lowpolycloud — APPROVED** [review]
Looks good! This will be very helpful

**Pull request merged**
